kind: Namespace
apiVersion: v1
metadata:
  name: httpd
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
   name: webserver-deployment 
   namespace: httpd
spec: 
  selector:
      matchLabels:
         app: web
  replicas: 2 
  template: 
   metadata: 
    labels: 
      app: web 
   spec: 
    containers: 
      - name: apache 
        image: httpd 
        ports: 
         - containerPort: 80 
        volumeMounts: 
          - name: log 
            mountPath: /var/log/apache2 
    volumes: 
     - name: log 
       emptyDir: {} 
--- 
apiVersion: v1 
kind: Service 
metadata: 
 namespace: httpd
 name: webserver 
 labels: 
   app: web 
spec: 
 ports: 
  - port: 80 
    protocol: TCP 
    targetPort: 80 
 type: LoadBalancer
 selector: 
  app: web